hostel_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
	path('', views.hostel_home, name='hostel-home'),
	path('register/<str:role>/', views.registerView, name='register'),
	path('login/<str:role>/', views.loginView, name='login'),
	path('logout/', views.logoutView, name='logout'),
	path('hostels/', views.HostelListView.as_view(), name='hostel-list'),
    path('add_hostel/', views.HostelCreateView.as_view(), name='add-hostel'),
    path('add_services/<int:pk>/', views.add_services, name='add-services'),
    path('add_room/<int:pk>/', views.add_room, name='add-room'),
    path('add_hostelimage/<int:pk>/', views.add_hostelimages, name='add-images'),
	path('hostels/<int:pk>/', views.HostelDetailView.as_view(), name='hostel-detail'),
    path('booking/<int:pk>/', views.book_room, name='book-room'),
	path('confirm_booking/<int:pk>/', views.confirm_booking, name='confirm-booking'),
	path('dashboard/', views.dashboard, name='dashboard'),
    path('profile/',views.profile,name='profile'),
]

hostels_locator/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('hostel_app.urls')),
]

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

payment/urls.py
# dj_razorpay/urls.py

from django.urls import path
from payment import views

urlpatterns = [
	path('', views.homepage, name='payment'),
	path('paymenthandler/', views.paymenthandler, name='paymenthandler'),
]

hostel_app/models.py
from django.template.loader import render_to_string
from django.core.mail import send_mail
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.conf import settings
# Create your models here.


class Hostel(models.Model):
    name = models.CharField(max_length=50)
    cover = models.ImageField(upload_to='cover', default='default.png')
    services = models.ManyToManyField("Service")
    location = models.ForeignKey(
        'Location', on_delete=models.SET_NULL, null=True)
    address = models.CharField(max_length=250, null=True)
    owner = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("hostel-detail", kwargs={"pk": self.pk})

    class Meta:
        verbose_name = 'Hostel'
        verbose_name_plural = 'Hostels'
        ordering = ['name']


class RoomCategory(models.Model):
    name = models.CharField(max_length=50)
    description = models.TextField(blank=True, null=True)
    quantity = models.IntegerField()
    price = models.PositiveIntegerField()
    hostel = models.ForeignKey(Hostel, on_delete=models.CASCADE)

    def __str__(self):
        return self.name
    
    def get_rooms_left(self):
        return self.quantity - self.booking_set.count()

    class Meta:
        verbose_name = 'Room_category'
        verbose_name_plural = 'Room_categories'


class Booking(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    room = models.ForeignKey(RoomCategory, on_delete=models.CASCADE)
    start_date = models.DateField()
    end_date = models.DateField()

    def save(self, *args, **kwargs):

        # Send email to the user
        subject = 'Booking confirmation'
        from_email = 'from@example.com'
        html_message = render_to_string('booking_confirmation_email.html', {
            'room': self.room, 'user': self.user, 'start_date': self.start_date, 'end_date': self.end_date})
        recipient_list = [self.user.email]
        send_mail(subject, message=None, html_message=html_message,
                  from_email=from_email, recipient_list=recipient_list)

        return super().save(*args, **kwargs)


    def __str__(self):
        return f" {self.user}has booked {self.room} from {self.start_date} to {self.end_date}"


class Location(models.Model):
    name = models.CharField(max_length=150, blank=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'UserLocation'
        verbose_name_plural = 'UserLocations'


class Service(models.Model):
    name = models.CharField(max_length=50)
    description = models.TextField()

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Service'
        verbose_name_plural = 'Services'


class HostelImage(models.Model):
    image= models.ImageField(upload_to='images/')
    hostel = models.ForeignKey(Hostel, on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'HostelImage'
        verbose_name_plural = 'HostelImages'


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    role = models.CharField(default="guest", max_length=50)
    profile_pic = models.ImageField(
        upload_to='profile/', default='default.png')
    cover = models.ImageField(upload_to='cover/', default='default.png')
    phone = models.CharField(max_length=20, null=True)

    def __str__(self):
        return self.get_username()


class Review(models.Model):
    pass

hostel_app/forms.py
from django import forms
from django.shortcuts import redirect,render
from .models import Hostel, HostelImage, Location,Booking, RoomCategory
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class HostelForm(forms.ModelForm):

    name = forms.CharField(widget=forms.TextInput(
        attrs={'class': 'form-control', 'placeholder': 'Hostel Name'}), label='Name *')
    cover = forms.ImageField(widget=forms.ClearableFileInput(
        attrs={'class': 'form-control'}), label='Cover *')
    address = forms.CharField(widget=forms.TextInput(
        attrs={'class': 'form-control', 'placeholder': 'Hostel Address'}), label='Address *')
    location = forms.ModelChoiceField(widget=forms.Select(
        attrs={'class': 'form-select', 'autofocus': ''}), queryset=Location.objects.all(), empty_label="Pick a city", label='Location *')

    class Meta:
        model = Hostel
        fields = ("name", "cover", "address", "location")

# #Create forms for creating and updating bookings
# class BookingForm(forms.ModelForm):
#     class Meta:
#         model = Booking
#         fields = ['room', 'start_date', 'end_date', ]
#         room = forms.ModelChoiceField(queryset=Room.objects.all())
#         start_date = forms.DateField()
#         end_date = forms.DateField()

#     def clean(self):
#         cleaned_data = super().clean()
#         room = cleaned_data.get('room')
#         check_in = cleaned_data.get('check_in')
#         check_out = cleaned_data.get('check_out')

# def book_room(room, check_in, check_out, user):
#     booking = Booking.objects.create(room=room, check_in=check_in, check_out=check_out, user=user)
#     room.bookings.add(booking)
#     room.save()



class UserForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for field_name in self.fields:
            field = self.fields[field_name]
            field.widget.attrs['class'] = 'form-control'
            
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'username', 'email')


class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField()



class RoomCategoryForm(forms.ModelForm):
    
    name = forms.CharField(widget=forms.TextInput(
        attrs={'class': 'form-control', 'placeholder': 'Room Name'}), label='Name *')
    
    description = forms.CharField(widget=forms.Textarea(
        attrs={'class': 'form-control', 'placeholder': 'Room Description'}), label='Description *')
    
    price = forms.IntegerField(widget=forms.NumberInput(
        attrs={'class': 'form-control', 'placeholder': 'Room Price'}), label='Price *')
    
    quantity = forms.IntegerField(widget=forms.NumberInput(
        attrs={'class': 'form-control', 'placeholder': 'Room Quantity'}), label='Quantity *')
    
    
    
    class Meta:
        model = RoomCategory
        exclude = ('hostel',)

class HostelImageForm(forms.ModelForm):
    image = forms.FileField(widget=forms.ClearableFileInput(
        attrs={'multiple': True}), required=False)
    
    class Meta:
        model = HostelImage
        exclude = ('hostel',)

hostel_app/views.py
from datetime import datetime
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic
from django.views.generic import DetailView
from django.contrib.auth import authenticate, login, logout, get_user_model
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect
from django.http import HttpResponseRedirect
from hostel_app.forms import HostelImageForm, LoginForm, RoomCategoryForm, UserForm, HostelForm
from .models import Booking, Hostel, Location, RoomCategory, UserProfile, Service, User


# create a view in Django that accepts location data via POST request and saves it to the database

##################################################################################
####################### Hostel Views            ##################################
##################################################################################


def hostel_home(request):
    context = {}
    context['hostels'] = Hostel.objects.all()
    return render(request, 'hostel_home.html', context)


class HostelCreateView(LoginRequiredMixin, generic.CreateView):
    model = Hostel
    form_class = HostelForm

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)


class HostelListView(generic.ListView):
    model = Hostel
    template_name = "hostel_list.html"
    paginate_by = 9

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        query = self.request.GET.get("query")
        lat = self.request.GET.get("lat")
        long = self.request.GET.get("lng")
        nearby = self.request.GET.get("nearby")
        try:
            user_location = get_location(lat, long)
            context['show_near'] = nearby
            context['nearby'] = Hostel.objects.filter(
                location__name__icontains=user_location)
            context['user_location'] = user_location
        except:
            pass
        context['locations'] = Location.objects.all()
        context['select_location'] = self.request.GET.get("location")
        if query:
            context["query"] = query
        return context

    def get_queryset(self):
        queryset = super().get_queryset()
        query = self.request.GET.get("query")
        location = self.request.GET.get("location")
        if query:
            queryset = queryset.filter(name__icontains=query)

        if location:
            queryset = queryset.filter(location__name__icontains=location)

        return queryset


class HostelDetailView(DetailView):
    model = Hostel
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['services'] = Service.objects.all()
        context['room_form'] = RoomCategoryForm()
        context['image_form'] = HostelImageForm()
        if self.request.user.is_authenticated:
            context["owner"] = Hostel.objects.filter(owner=self.request.user)
            context['guest'] = Booking.objects.filter(user=self.request.user,room__hostel__id = self.kwargs['pk'])
        return context
    

def get_location(lat, long):
    import geocoder
    g = geocoder.osm([lat, long], method='reverse')
    return g.json['state']


def add_hostel(request):
    if request.method == 'POST':
        form = HostelForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('hostel_list')
    else:
        form = HostelForm()
    return render(request, 'add_hostel.html', {'form': form})

def add_services(request,pk):
    if request.method == 'POST':
        hostel = Hostel.objects.get(id=pk)
        for k,v in request.POST.items():
            if k == 'csrfmiddlewaretoken':
                continue
            else:
                id = k[-1]
                services = Service.objects.get(id=id)
                hostel.services.add(services)
        
        hostel.save()
                
        return redirect('hostel-detail',pk)
    
def add_room(request,pk):
    if request.method == 'POST':
        form = RoomCategoryForm(request.POST)
        if form.is_valid():
            room = form.save(commit=False)
            room.hostel = Hostel.objects.get(id=pk)
            room.save()
            return redirect('hostel-detail',pk)
        
def add_hostelimages(request,pk):
    hostel = get_object_or_404(Hostel, pk=pk)
    if request.method == 'POST':
        form = HostelImageForm(request.POST, request.FILES)
        if form.is_valid():
            image = form.save(commit=False)
            image.hostel = hostel  # Associate the image with the hostel
            image.save()
            return redirect('hostel-detail', pk=pk)
        

# def hostel_detail(request, hostel_id):
#     hostel = Hostel.objects.get(id=hostel_id)
#     rooms = Room.objects.filter(hostel=hostel)
#     return render(request, 'hostel_detail.html', {'hostel': hostel, 'rooms': rooms})


# def room_detail(request, room_id):
#     room = Room.objects.get(id=room_id)
#     bookings = Booking.objects.filter(room=room)
#     return render(request, 'room_detail.html', {'room': room, 'bookings': bookings})

# one for displaying the details of a specific hostel and its rooms,
# and one for displaying the details of a specific room and its bookings

#manage guests

def admin_report(request):
    num_hostels = Hostel.objects.count()
    num_guests = User.objects.count()
    context = {'num_hostels': num_hostels, 'num_guests': num_guests}
    return render(request, 'dashboard.html', context)

@login_required(login_url='login')
def dashboard(request):
    context = {}
    if request.user.userprofile.role == 'guest':
        return render(request, 'profile.html')

    if request.method == "POST":
        form = HostelForm(request.POST, request.FILES)
        if form.is_valid():
            hostel = form.save(commit=False)
            hostel.owner = request.user  # add the owner field
            hostel.save()
            return HttpResponseRedirect(reverse('hostel-detail', args=[str(hostel.id)]))
    else:
        form = HostelForm()
        
    num_guests = User.objects.count()
    num_hostels = Hostel.objects.count()
    context = {'num_guests': num_guests, 'num_hostels': num_hostels}
 

    context['locations'] = Location.objects.all()
    context['hostels'] = Hostel.objects.filter(
        owner=request.user)  # filter hostels by owner
    context['form'] = form

    return render(request, 'dashboard.html', context)


def profile(request):
    return render(request, 'profile.html')


def book_room(request,pk):
    room = RoomCategory.objects.get(id=pk)
    booked = request.GET.get('booked')
    if booked:
        booking = Booking.objects.create(user=request.user, room=room, start_date=datetime.today(
        ).date(), end_date=datetime.today().date())
        booking.save()
        return redirect('hostel-detail',pk=room.hostel.id)
    return render(request,'book_room.html',{'pk':pk,'category':room})

@login_required(login_url='login')
def confirm_booking(request,pk):
    if request.method == 'POST':
        room = RoomCategory.objects.get(id=pk)
        user = request.user
        print(request.POST['start_date'])
        start = request.POST.get('start_date')
        end = request.POST.get('end_date')
        booking = Booking.objects.create(room=room,user=user,start_date=start,end_date=end)
        booking.save()
        return redirect('hostel-detail',room.hostel.id)


def registerView(request, role):
    context = {}
    context['role'] = role
    if request.method == 'POST':
        form = UserForm(request.POST)

        if form.is_valid():
            new_user = form.save(commit=True)
            new_user = authenticate(username=form.cleaned_data['username'],
                                    password=form.cleaned_data['password1'],)

            if new_user is not None:
                # Create userprofile
                user_profile = UserProfile.objects.create(
                    user=new_user, role=role)
                user_profile.save()
                login(request, new_user)

            return redirect('hostel-home')
        else:
            context['form'] = form
    else:
        context['form'] = UserForm()

    return render(request, 'register.html', context=context)



def loginView(request, role):
    if request.user.is_authenticated:
        return redirect('hostel-home')
    context = {}
    context['role'] = role
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            new_user = form.clean()
            try:
                new_user = authenticate(
                    username=form.cleaned_data['username'], password=form.cleaned_data['password'],)
                login(request, new_user)

            except:
                context['usererror'] = get_user_model().objects.filter(
                    username=form.cleaned_data['username'])
                context['errors'] = True
            else:
                return redirect('hostel-home')

    return render(request, 'login.html', context=context)


def logoutView(request):
    logout(request)
    return redirect('hostel-home')

hostel_app/templates/hostel_app/hostel_detail.html
{% extends 'hostel_base.html' %}
{% load static %}
{% block navbar %}
<div class="collapse navbar-collapse" id="navbarResponsive">
	<ul class="navbar-nav ms-auto">
		<li class="nav-item nav-link">
			<a class="nav-link active" href="{% url 'hostel-list' %}">Hostels</a>
		</li>

		{% if user.is_authenticated %}


		{% if user.userprofile.role == 'host' %}
		<li class="nav-item nav-link">
			<a class="nav-link" href="{% url 'dashboard' %}">Host Dashboard</a>
		</li>
		{% elif user.userprofile.role == 'guest' %}
		<li class="nav-item nav-link">
			<a class="nav-link" href="{% url 'dashboard' %}">Guest Dashboard</a>
		</li>

		{% endif %}
		<li class="nav-item nav-link">
			<a class="nav-link" href="{% url 'profile' %}">Profile</a>
		</li>
		<li class="nav-item nav-link">
			<a class="nav-link" href="{% url 'logout' %}">Logout</a>
		</li>
		{% else %}

		<li class="nav-item nav-link">
			<a class="nav-link" href="{% url 'login' role='host' %}">Host Login</a>
		</li>
		<li class="nav-item nav-link">
			<a class="nav-link" href="{% url 'login' role='guest' %}">Guest login</a>
		</li>
		{% endif %}

		<li class="nav-item"></li>
	</ul>
</div>
{% endblock navbar %}
{% block main %}
<section class="text-center content-section" id="about" style="padding: 200px 0 0">
	<h2>{{hostel}}</h2>
	<div class="container">
		<div class="d-flex justify-content-evenly" style="margin: 20px 0px">
			<img src="{{hostel.cover.url}}" class="img-fluid" alt="...">
		</div>
	</div>
</section>
<div class="row mx-0 px-4">
	<div class="col-md-6 row">
		<div class="col-12 mb-2">
			<div class="card bg-dark">
				<div class="card-body">
					<h5 class="card-title">Hostel Address</h5>
					<p class="card-text">
						<span class="fw-bold">Location</span> : {{hostel.location}}
					</p>
					<p class="card-text">
						<span class="fw-bold">Address</span> : {{hostel.address}}
					</p>
				</div>
			</div>
		</div>
		<div class="col-12 mb-2">
			<div class="card bg-dark">
				<div class="card-body">
					<h5 class="card-title">Gallery</h5>

					{% if owner%}
					<!-- Modal trigger button -->
					<button type="button" class="btn btn-primary btn-md my-2" data-bs-toggle="modal"
						data-bs-target="#imageFormModal">
						Upload Images
					</button>

					<!-- Modal Body -->
					<!-- if you want to close by clicking outside the modal, delete the last endpoint:data-bs-backdrop and data-bs-keyboard -->
					<div class="modal fade" id="imageFormModal" tabindex="-1" data-bs-backdrop="static"
						data-bs-keyboard="false" role="dialog" aria-labelledby="modalTitleId" aria-hidden="true">
						<div class="modal-dialog modal-dialog-centered" role="document">
							<form action="{% url 'add-images' hostel.id %}" method="post" enctype="multipart/form-data"
								class="modal-content bg-dark">
								<div class="modal-header">
									<h5 class="modal-title" id="modalTitleId">Add hostel images</h5>
									<button type="button" class="btn-close" data-bs-dismiss="modal"
										aria-label="Close"></button>
								</div>
								<div class="modal-body">
									{% csrf_token %}
									<label for="images">Images:</label>
									<input id="images" class="form-control" name="image" type="file" accept="image/*"
										multiple>
								</div>
								<div class="modal-footer">
									<button type="button" class="btn btn-secondary"
										data-bs-dismiss="modal">Close</button>
									<button type="submit" class="btn btn-primary">Save</button>
								</div>
							</form>
						</div>
					</div>


					<!-- Optional: Place to the bottom of scripts -->
					<script>
						const myModal = new bootstrap.Modal(document.getElementById('imageFormModal'), options)

					</script>
					{% endif %}


					{% if hostel.hostelimage_set.all %}
					<div id="galleryCarousel" class="carousel slide" data-bs-ride="carousel">
						<ol class="carousel-indicators">
							<li data-bs-target="#galleryCarousel" data-bs-slide-to="0" class="active"
								aria-current="true" aria-label="First slide"></li>
							<li data-bs-target="#galleryCarousel" data-bs-slide-to="1" aria-label="Second slide"></li>
							<li data-bs-target="#galleryCarousel" data-bs-slide-to="2" aria-label="Third slide"></li>
						</ol>
						<div class="carousel-inner" role="listbox">

							{% for image in hostel.hostelimage_set.all %}
							<div class="carousel-item {% if forloop.first %}active{% endif %}">
								<img src="{{image.image.url}}" class="w-100 d-block" alt="Slide {{forloop.counter}}">
							</div>
							{% endfor %}


						</div>
						<button class="carousel-control-prev" type="button" data-bs-target="#galleryCarousel"
							data-bs-slide="prev">
							<span class="carousel-control-prev-icon" aria-hidden="true"></span>
							<span class="visually-hidden">Previous</span>
						</button>
						<button class="carousel-control-next" type="button" data-bs-target="#galleryCarousel"
							data-bs-slide="next">
							<span class="carousel-control-next-icon" aria-hidden="true"></span>
							<span class="visually-hidden">Next</span>
						</button>
					</div>
					{% endif %}




				</div>
			</div>
		</div>
	</div>

	{% if owner %}
	<div class="col-md-6 row">
		<div class="col-12 mb-2">
			<div class="card bg-dark">
				<div class="card-body">
					<h5 class="card-title">Hostel Services</h5>

					{% if hostel.services.all %}
					<p class="card-text">
						{% for service in hostel.services.all %}
						<span class="badge bg-primary">{{service}}</span>
						{% endfor %}
					</p>
					{% else %}
					<p class="card-text">Select services below</p>
					<form action="{% url 'add-services' hostel.id%}" method="post">
						{% csrf_token %}
						<div class="btn-group" role="group" aria-label="Basic checkbox toggle button group">
							{% for service in services %}
							<input type="checkbox" class="btn-check" id="btncheck{{service.id}}"
								name="service{{service.id}}" autocomplete="off">
							<label class="btn btn-outline-primary" for="btncheck{{service.id}}">{{service}}</label>
							{% endfor %}

						</div>
						<button type="submit" class="btn btn-primary">Save</button>
					</form>
					{% endif %}


				</div>
			</div>
		</div>
		<div class="col-12 mb-2">
			<div class="card bg-dark">
				<div class="card-body">
					<h5 class="card-title">Hostel Rooms</h5>

					{% if hostel.roomcategory_set.all %}
					<p class="card-text">
						{% for category in hostel.roomcategory_set.all %}
						<span class="badge bg-primary">{{category}}</span>
						{% endfor %}
					</p>
					<p class="card-text py-2">
						<!-- Button trigger modal -->
						<button type="button" class="btn btn-primary" data-bs-toggle="modal"
							data-bs-target="#roomTypemodal">
							Add Room Type
						</button>

						<!-- Modal -->
					<div class="modal fade" id="roomTypemodal" tabindex="-1" aria-labelledby="roomTypemodalLabel"
						aria-hidden="true">
						<div class="modal-dialog        ">
							<form method="post" action="{% url 'add-room' hostel.pk %}" class="modal-content text-dark">
								{% csrf_token %}
								<div class="modal-header">
									<h5 class="modal-title" id="roomTypemodalLabel">Add Room</h5>
									<button type="button" class="btn-close" data-bs-dismiss="modal"
										aria-label="Close"></button>
								</div>
								<div class="modal-body">
									{{room_form}}
								</div>
								<div class="modal-footer">
									<button type="button" class="btn btn-secondary"
										data-bs-dismiss="modal">Close</button>
									<button type="submit" class="btn btn-primary">Save</button>
								</div>
							</form>
						</div>
					</div>
					</p>

					{% endif %}

				</div>
			</div>
		</div>
	</div>
	{% else %}
	<div class="col-md-6">
		<div class="col-12 mb-2">
			<div class="card bg-dark">
				<div class="card-body">
					<h5 class="card-title">Hostel Services</h5>
					{% for service in hostel.services.all %}
					<span class="badge bg-primary">{{service}}</span>
					{% endfor %}

				</div>
			</div>
		</div>
		<div class="col-12 mb-2">
			<div class="card bg-dark">
				<div class="card-body">
					<h5 class="card-title">Hostel Rooms</h5>

					{% if hostel.roomcategory_set.all and not guest%}
					<p class="card-text">
						{% for category in hostel.roomcategory_set.all %}
						<!-- Button trigger modal -->
						<button type="button" class="btn btn-primary" data-bs-toggle="modal"
							data-bs-target="#room{{category.id}}">
							<span class="badge bg-primary">{{category}}</span>
						</button>

						<!-- Modal -->
					<div class="modal fade" id="room{{category.id}}" tabindex="-1"
						aria-labelledby="room{{category.id}}Label" aria-hidden="true">
						<div class="modal-dialog modal-dialog-centered      ">
							<div class="modal-content bg-dark">
								<div class="modal-header">
									<h5 class="modal-title" id="room{{category.id}}Label">Book {{category}} room</h5>
									<button type="button" class="btn-close" data-bs-dismiss="modal"
										aria-label="Close"></button>
								</div>
								<div class="modal-body">
									<div class="p-2">
										<div class="container-fluid">
											<div class="lead">
												<div>
													<span>Name : </span>{{category.name}}
												</div>
												<div>
													<span>Description : </span>{{category.description}}
												</div>
												<div>
													<span>Price : </span>{{category.price}}
												</div>
												<div>
													<span>Rooms Left : </span>{{category.get_rooms_left}}
												</div>
											</div>

											<div class="text-center">
												<a href="{% url 'book-room' category.pk %}" class="btn btn-primary btn-lg" type="button">Book</a>

											</div>
										</div>
									</div>
								</div>
								
							</div>
						</div>
					</div>
					{% endfor %}
					</p>

					{% endif %}
					
					{% if guest %}
						
						{% for guest_obj in guest %}
							You have booked the room {{guest_obj.room.name}}
						{% endfor %}
							
					{% endif %}
						

				</div>
			</div>
		</div>
	</div>
	{% endif %}

</div>
{% endblock main %}

{% block contact %}
<section class="text-center content-section" id="contact" style="height: 0">
	<div class="container">
		<div class="row">
			<div class="col-lg-8 mx-auto">
				<h2>Contact Host</h2>
				<p class="text-light" style="padding: 10px 0">
					For more information on the hostel kindly contact the owner
					using method given below. Remember to keep things
					professional.
				</p>
				<ul class="list-inline banner-social-buttons">
					<li class="list-inline-item">&nbsp;</li>
					<li class="list-inline-item">
						&nbsp;<button class="btn btn-primary btn-lg btn-default" type="button" style="width: 214px">
							<i class="fa fa-whatsapp fa-fw"></i><span class="network-name">&nbsp;Whatsapp</span>
						</button>
					</li>
					<li class="list-inline-item">&nbsp;</li>
				</ul>
			</div>
		</div>
	</div>
</section>
{% endblock contact %}

hostel_app/templates/hostel_app/hostel_form.html
{% extends 'hostel_base.html' %}
{% load static %}
{% block navbar %}
<div class="collapse navbar-collapse" id="navbarResponsive">
	<ul class="navbar-nav ms-auto">
		<li class="nav-item nav-link">
			<a class="nav-link active" href="{% url 'hostel-list' %}">Hostels</a>
		</li>

		{% if user.is_authenticated %}


		{% if user.userprofile.role == 'host' %}
		<li class="nav-item nav-link">
			<a class="nav-link" href="{% url 'dashboard' %}">Host Dashboard</a>
		</li>


		{% endif %}
		<li class="nav-item nav-link">
			<a class="nav-link" href="{% url 'profile' %}">Profile</a>
		</li>
		<li class="nav-item nav-link">
			<a class="nav-link" href="{% url 'logout' %}">Logout</a>
		</li>
		{% else %}

		<li class="nav-item nav-link">
			<a class="nav-link" href="{% url 'login' role='host' %}">Host Login</a>
		</li>
		<li class="nav-item nav-link">
			<a class="nav-link" href="{% url 'login' role='guest' %}">Guest login</a>
		</li>
		{% endif %}

		<li class="nav-item"></li>
	</ul>
</div>
{% endblock navbar %}
{% block main %}
<div class="py-5"></div>
<div class="container-fluid">
	<div class="d-sm-flex justify-content-between align-items-center mb-4">
		<h3 class="text-light mb-0">Hostel information</h3>
	</div>
	<form method="post" enctype="multipart/form-data">
		{% csrf_token %}
		<div class="card shadow mb-3 p-3 rounded">
			<div class="card-header py-3">
				<p class="text-primary m-0 fw-bold">Fill in the required fields *</p>
			</div>
			{{form}}
			<div class="my-2 text-center">
				<button class="btn btn-primary" type="submit">
					Save
				</button>
			</div>
		</div>
	</form>
</div>
{% endblock %}